### PR TITLE
Fix node order + edit all path variables

### PR DESCRIPTION
**Pull request by Ignoble61**
As reported by Dave Blake on the [forums](http://forum.kodi.tv/showthread.php?tid=224512&pid=2417003#pid2417003)

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Thanks for looking at this so quickly.

For 2) in the forum post "Roles" is 'musicdb://roles' with text ID 29994 for the label.  Maybe worth adding to this PR? Otherwise yes, I see how to do that now.

For your interest: if music files are fully tagged (using COMPOSER (TCOM), CONDUCTOR (TPE3), REMIXER (TPE4), ARRANGER, ENGINEER etc. or PERFORMER=artist (instrument) (TIPL and TMCL) tags then Kodi now stores that info as the role of the artist. The roles node is then a list of the various ways people (or bands etc.) contribute to songs

**Comment by DaveTBlake** [comment]
Tested and works fine, thanks @Ignoble61

**Comment by Ignoble61** [comment]
Dave, I've added Roles locally as a selectable path but any component I add to it doesn't appear to have any effect. Can you confirm that - to take an example - adding the years component should be as the other paths and so `musicdb://roles/?year=1978`. Assuming it is (and it's the very likely scenario that my music is incredibly badly tagged which mean it's not working as expected here) I'll add it to the PR.

**Comment by DaveTBlake** [comment]
It is working correctly in the way that the roles node (and others) is currently implemented.

Not every component (option) has meaning for every node, e.g. `musicdb://artists/?year=1978` does not do anything at artist level, you just see all the artists. But the options get passed down to the next node level when navigating, so click on an artist and you will see the albums for that artist for 1978 - year does apply to albums and songs.

Having said that, roles node is new and I still have some tweaking in core to do to get the options passed down correctly from roles - I had not tested roles with year before! So thanks for that.

**Comment by Ignoble61** [comment]
PR updated.

**Comment by ronie** [comment]
thanx!

i'll bump the version and submit it to our repo.

**Pull request merged**
